source 'https://rubygems.org'

gem 'rails', '>= 5.0.0.beta1', '< 5.1'
gem 'pg', '~> 0.18'
gem 'puma'
gem 'bcrypt', '~> 3.1.7'
gem 'rack-cors'
gem 'active_model_serializers', '~> 0.10.0.rc2'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'spring'
end
